/**
 *
 *  Ticket.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Ticket.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::rail_ticket;

const std::string Ticket::Cols::_id = "id";
const std::string Ticket::Cols::_trip = "trip";
const std::string Ticket::Cols::_seatType = "seatType";
const std::string Ticket::Cols::_carriage = "carriage";
const std::string Ticket::Cols::_seatPosition = "seatPosition";
const std::string Ticket::Cols::_available = "available";
const std::string Ticket::Cols::_startStation = "startStation";
const std::string Ticket::Cols::_endStation = "endStation";
const std::string Ticket::primaryKeyName = "id";
const bool Ticket::hasPrimaryKey = true;
const std::string Ticket::tableName = "ticket";

const std::vector<typename Ticket::MetaData> Ticket::metaData_={
{"id","int32_t","int",4,1,1,1},
{"trip","std::string","varchar(255)",255,0,0,1},
{"seatType","int8_t","tinyint",1,0,0,1},
{"carriage","int8_t","tinyint",1,0,0,1},
{"seatPosition","std::string","char(1)",0,0,0,1},
{"available","int32_t","int",4,0,0,1},
{"startStation","std::string","varchar(255)",255,0,0,0},
{"endStation","std::string","varchar(255)",255,0,0,0}
};
const std::string &Ticket::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Ticket::Ticket(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(r["trip"].as<std::string>());
        }
        if(!r["seatType"].isNull())
        {
            seattype_=std::make_shared<int8_t>(r["seatType"].as<int8_t>());
        }
        if(!r["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>(r["carriage"].as<int8_t>());
        }
        if(!r["seatPosition"].isNull())
        {
            seatposition_=std::make_shared<std::string>(r["seatPosition"].as<std::string>());
        }
        if(!r["available"].isNull())
        {
            available_=std::make_shared<int32_t>(r["available"].as<int32_t>());
        }
        if(!r["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(r["startStation"].as<std::string>());
        }
        if(!r["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(r["endStation"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            trip_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            seattype_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            carriage_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            seatposition_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            available_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            startstation_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            endstation_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Ticket::Ticket(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trip_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            seattype_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            seatposition_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            available_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

Ticket::Ticket(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trip"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(pJson["trip"].asString());
        }
    }
    if(pJson.isMember("seatType"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["seatType"].isNull())
        {
            seattype_=std::make_shared<int8_t>((int8_t)pJson["seatType"].asInt64());
        }
    }
    if(pJson.isMember("carriage"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson["carriage"].asInt64());
        }
    }
    if(pJson.isMember("seatPosition"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["seatPosition"].isNull())
        {
            seatposition_=std::make_shared<std::string>(pJson["seatPosition"].asString());
        }
    }
    if(pJson.isMember("available"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["available"].isNull())
        {
            available_=std::make_shared<int32_t>((int32_t)pJson["available"].asInt64());
        }
    }
    if(pJson.isMember("startStation"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson["startStation"].asString());
        }
    }
    if(pJson.isMember("endStation"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson["endStation"].asString());
        }
    }
}

void Ticket::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trip_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            seattype_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            seatposition_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            available_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

void Ticket::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trip"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(pJson["trip"].asString());
        }
    }
    if(pJson.isMember("seatType"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["seatType"].isNull())
        {
            seattype_=std::make_shared<int8_t>((int8_t)pJson["seatType"].asInt64());
        }
    }
    if(pJson.isMember("carriage"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson["carriage"].asInt64());
        }
    }
    if(pJson.isMember("seatPosition"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["seatPosition"].isNull())
        {
            seatposition_=std::make_shared<std::string>(pJson["seatPosition"].asString());
        }
    }
    if(pJson.isMember("available"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["available"].isNull())
        {
            available_=std::make_shared<int32_t>((int32_t)pJson["available"].asInt64());
        }
    }
    if(pJson.isMember("startStation"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson["startStation"].asString());
        }
    }
    if(pJson.isMember("endStation"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson["endStation"].asString());
        }
    }
}

const int32_t &Ticket::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Ticket::getId() const noexcept
{
    return id_;
}
void Ticket::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Ticket::PrimaryKeyType & Ticket::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Ticket::getValueOfTrip() const noexcept
{
    const static std::string defaultValue = std::string();
    if(trip_)
        return *trip_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Ticket::getTrip() const noexcept
{
    return trip_;
}
void Ticket::setTrip(const std::string &pTrip) noexcept
{
    trip_ = std::make_shared<std::string>(pTrip);
    dirtyFlag_[1] = true;
}
void Ticket::setTrip(std::string &&pTrip) noexcept
{
    trip_ = std::make_shared<std::string>(std::move(pTrip));
    dirtyFlag_[1] = true;
}

const int8_t &Ticket::getValueOfSeattype() const noexcept
{
    const static int8_t defaultValue = int8_t();
    if(seattype_)
        return *seattype_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Ticket::getSeattype() const noexcept
{
    return seattype_;
}
void Ticket::setSeattype(const int8_t &pSeattype) noexcept
{
    seattype_ = std::make_shared<int8_t>(pSeattype);
    dirtyFlag_[2] = true;
}

const int8_t &Ticket::getValueOfCarriage() const noexcept
{
    const static int8_t defaultValue = int8_t();
    if(carriage_)
        return *carriage_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Ticket::getCarriage() const noexcept
{
    return carriage_;
}
void Ticket::setCarriage(const int8_t &pCarriage) noexcept
{
    carriage_ = std::make_shared<int8_t>(pCarriage);
    dirtyFlag_[3] = true;
}

const std::string &Ticket::getValueOfSeatposition() const noexcept
{
    const static std::string defaultValue = std::string();
    if(seatposition_)
        return *seatposition_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Ticket::getSeatposition() const noexcept
{
    return seatposition_;
}
void Ticket::setSeatposition(const std::string &pSeatposition) noexcept
{
    seatposition_ = std::make_shared<std::string>(pSeatposition);
    dirtyFlag_[4] = true;
}
void Ticket::setSeatposition(std::string &&pSeatposition) noexcept
{
    seatposition_ = std::make_shared<std::string>(std::move(pSeatposition));
    dirtyFlag_[4] = true;
}

const int32_t &Ticket::getValueOfAvailable() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(available_)
        return *available_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Ticket::getAvailable() const noexcept
{
    return available_;
}
void Ticket::setAvailable(const int32_t &pAvailable) noexcept
{
    available_ = std::make_shared<int32_t>(pAvailable);
    dirtyFlag_[5] = true;
}

const std::string &Ticket::getValueOfStartstation() const noexcept
{
    const static std::string defaultValue = std::string();
    if(startstation_)
        return *startstation_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Ticket::getStartstation() const noexcept
{
    return startstation_;
}
void Ticket::setStartstation(const std::string &pStartstation) noexcept
{
    startstation_ = std::make_shared<std::string>(pStartstation);
    dirtyFlag_[6] = true;
}
void Ticket::setStartstation(std::string &&pStartstation) noexcept
{
    startstation_ = std::make_shared<std::string>(std::move(pStartstation));
    dirtyFlag_[6] = true;
}
void Ticket::setStartstationToNull() noexcept
{
    startstation_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Ticket::getValueOfEndstation() const noexcept
{
    const static std::string defaultValue = std::string();
    if(endstation_)
        return *endstation_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Ticket::getEndstation() const noexcept
{
    return endstation_;
}
void Ticket::setEndstation(const std::string &pEndstation) noexcept
{
    endstation_ = std::make_shared<std::string>(pEndstation);
    dirtyFlag_[7] = true;
}
void Ticket::setEndstation(std::string &&pEndstation) noexcept
{
    endstation_ = std::make_shared<std::string>(std::move(pEndstation));
    dirtyFlag_[7] = true;
}
void Ticket::setEndstationToNull() noexcept
{
    endstation_.reset();
    dirtyFlag_[7] = true;
}

void Ticket::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Ticket::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "trip",
        "seatType",
        "carriage",
        "seatPosition",
        "available",
        "startStation",
        "endStation"
    };
    return inCols;
}

void Ticket::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrip())
        {
            binder << getValueOfTrip();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSeattype())
        {
            binder << getValueOfSeattype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCarriage())
        {
            binder << getValueOfCarriage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSeatposition())
        {
            binder << getValueOfSeatposition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAvailable())
        {
            binder << getValueOfAvailable();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStartstation())
        {
            binder << getValueOfStartstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEndstation())
        {
            binder << getValueOfEndstation();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Ticket::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Ticket::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrip())
        {
            binder << getValueOfTrip();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSeattype())
        {
            binder << getValueOfSeattype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCarriage())
        {
            binder << getValueOfCarriage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSeatposition())
        {
            binder << getValueOfSeatposition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAvailable())
        {
            binder << getValueOfAvailable();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStartstation())
        {
            binder << getValueOfStartstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEndstation())
        {
            binder << getValueOfEndstation();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Ticket::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrip())
    {
        ret["trip"]=getValueOfTrip();
    }
    else
    {
        ret["trip"]=Json::Value();
    }
    if(getSeattype())
    {
        ret["seatType"]=getValueOfSeattype();
    }
    else
    {
        ret["seatType"]=Json::Value();
    }
    if(getCarriage())
    {
        ret["carriage"]=getValueOfCarriage();
    }
    else
    {
        ret["carriage"]=Json::Value();
    }
    if(getSeatposition())
    {
        ret["seatPosition"]=getValueOfSeatposition();
    }
    else
    {
        ret["seatPosition"]=Json::Value();
    }
    if(getAvailable())
    {
        ret["available"]=getValueOfAvailable();
    }
    else
    {
        ret["available"]=Json::Value();
    }
    if(getStartstation())
    {
        ret["startStation"]=getValueOfStartstation();
    }
    else
    {
        ret["startStation"]=Json::Value();
    }
    if(getEndstation())
    {
        ret["endStation"]=getValueOfEndstation();
    }
    else
    {
        ret["endStation"]=Json::Value();
    }
    return ret;
}

Json::Value Ticket::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTrip())
            {
                ret[pMasqueradingVector[1]]=getValueOfTrip();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSeattype())
            {
                ret[pMasqueradingVector[2]]=getValueOfSeattype();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCarriage())
            {
                ret[pMasqueradingVector[3]]=getValueOfCarriage();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSeatposition())
            {
                ret[pMasqueradingVector[4]]=getValueOfSeatposition();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAvailable())
            {
                ret[pMasqueradingVector[5]]=getValueOfAvailable();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStartstation())
            {
                ret[pMasqueradingVector[6]]=getValueOfStartstation();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEndstation())
            {
                ret[pMasqueradingVector[7]]=getValueOfEndstation();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrip())
    {
        ret["trip"]=getValueOfTrip();
    }
    else
    {
        ret["trip"]=Json::Value();
    }
    if(getSeattype())
    {
        ret["seatType"]=getValueOfSeattype();
    }
    else
    {
        ret["seatType"]=Json::Value();
    }
    if(getCarriage())
    {
        ret["carriage"]=getValueOfCarriage();
    }
    else
    {
        ret["carriage"]=Json::Value();
    }
    if(getSeatposition())
    {
        ret["seatPosition"]=getValueOfSeatposition();
    }
    else
    {
        ret["seatPosition"]=Json::Value();
    }
    if(getAvailable())
    {
        ret["available"]=getValueOfAvailable();
    }
    else
    {
        ret["available"]=Json::Value();
    }
    if(getStartstation())
    {
        ret["startStation"]=getValueOfStartstation();
    }
    else
    {
        ret["startStation"]=Json::Value();
    }
    if(getEndstation())
    {
        ret["endStation"]=getValueOfEndstation();
    }
    else
    {
        ret["endStation"]=Json::Value();
    }
    return ret;
}

bool Ticket::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("trip"))
    {
        if(!validJsonOfField(1, "trip", pJson["trip"], err, true))
            return false;
    }
    else
    {
        err="The trip column cannot be null";
        return false;
    }
    if(pJson.isMember("seatType"))
    {
        if(!validJsonOfField(2, "seatType", pJson["seatType"], err, true))
            return false;
    }
    else
    {
        err="The seatType column cannot be null";
        return false;
    }
    if(pJson.isMember("carriage"))
    {
        if(!validJsonOfField(3, "carriage", pJson["carriage"], err, true))
            return false;
    }
    else
    {
        err="The carriage column cannot be null";
        return false;
    }
    if(pJson.isMember("seatPosition"))
    {
        if(!validJsonOfField(4, "seatPosition", pJson["seatPosition"], err, true))
            return false;
    }
    else
    {
        err="The seatPosition column cannot be null";
        return false;
    }
    if(pJson.isMember("available"))
    {
        if(!validJsonOfField(5, "available", pJson["available"], err, true))
            return false;
    }
    else
    {
        err="The available column cannot be null";
        return false;
    }
    if(pJson.isMember("startStation"))
    {
        if(!validJsonOfField(6, "startStation", pJson["startStation"], err, true))
            return false;
    }
    if(pJson.isMember("endStation"))
    {
        if(!validJsonOfField(7, "endStation", pJson["endStation"], err, true))
            return false;
    }
    return true;
}
bool Ticket::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Ticket::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("trip"))
    {
        if(!validJsonOfField(1, "trip", pJson["trip"], err, false))
            return false;
    }
    if(pJson.isMember("seatType"))
    {
        if(!validJsonOfField(2, "seatType", pJson["seatType"], err, false))
            return false;
    }
    if(pJson.isMember("carriage"))
    {
        if(!validJsonOfField(3, "carriage", pJson["carriage"], err, false))
            return false;
    }
    if(pJson.isMember("seatPosition"))
    {
        if(!validJsonOfField(4, "seatPosition", pJson["seatPosition"], err, false))
            return false;
    }
    if(pJson.isMember("available"))
    {
        if(!validJsonOfField(5, "available", pJson["available"], err, false))
            return false;
    }
    if(pJson.isMember("startStation"))
    {
        if(!validJsonOfField(6, "startStation", pJson["startStation"], err, false))
            return false;
    }
    if(pJson.isMember("endStation"))
    {
        if(!validJsonOfField(7, "endStation", pJson["endStation"], err, false))
            return false;
    }
    return true;
}
bool Ticket::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Ticket::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
