/**
 *
 *  Train.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Train.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::rail_ticket;

const std::string Train::Cols::_id = "id";
const std::string Train::Cols::_trip = "trip";
const std::string Train::Cols::_type = "type";
const std::string Train::Cols::_carriage = "carriage";
const std::string Train::Cols::_startStation = "startStation";
const std::string Train::Cols::_endStation = "endStation";
const std::string Train::Cols::_startTime = "startTime";
const std::string Train::Cols::_endTime = "endTime";
const std::string Train::Cols::_duration = "duration";
const std::string Train::Cols::_status = "status";
const std::string Train::primaryKeyName = "id";
const bool Train::hasPrimaryKey = true;
const std::string Train::tableName = "train";

const std::vector<typename Train::MetaData> Train::metaData_={
{"id","int32_t","int",4,1,1,1},
{"trip","std::string","varchar(255)",255,0,0,1},
{"type","std::string","varchar(255)",255,0,0,1},
{"carriage","int8_t","tinyint",1,0,0,1},
{"startStation","std::string","varchar(255)",255,0,0,1},
{"endStation","std::string","varchar(255)",255,0,0,1},
{"startTime","std::string","time",0,0,0,1},
{"endTime","std::string","time",0,0,0,1},
{"duration","std::string","time",0,0,0,1},
{"status","int8_t","tinyint",1,0,0,1}
};
const std::string &Train::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Train::Train(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(r["trip"].as<std::string>());
        }
        if(!r["type"].isNull())
        {
            type_=std::make_shared<std::string>(r["type"].as<std::string>());
        }
        if(!r["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>(r["carriage"].as<int8_t>());
        }
        if(!r["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(r["startStation"].as<std::string>());
        }
        if(!r["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(r["endStation"].as<std::string>());
        }
        if(!r["startTime"].isNull())
        {
            starttime_=std::make_shared<std::string>(r["startTime"].as<std::string>());
        }
        if(!r["endTime"].isNull())
        {
            endtime_=std::make_shared<std::string>(r["endTime"].as<std::string>());
        }
        if(!r["duration"].isNull())
        {
            duration_=std::make_shared<std::string>(r["duration"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<int8_t>(r["status"].as<int8_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            trip_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            type_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            carriage_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            startstation_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            endstation_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            starttime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            endtime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            duration_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            status_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
    }

}

Train::Train(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trip_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            starttime_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            endtime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            duration_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
}

Train::Train(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trip"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(pJson["trip"].asString());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("carriage"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson["carriage"].asInt64());
        }
    }
    if(pJson.isMember("startStation"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson["startStation"].asString());
        }
    }
    if(pJson.isMember("endStation"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson["endStation"].asString());
        }
    }
    if(pJson.isMember("startTime"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["startTime"].isNull())
        {
            starttime_=std::make_shared<std::string>(pJson["startTime"].asString());
        }
    }
    if(pJson.isMember("endTime"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["endTime"].isNull())
        {
            endtime_=std::make_shared<std::string>(pJson["endTime"].asString());
        }
    }
    if(pJson.isMember("duration"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["duration"].isNull())
        {
            duration_=std::make_shared<std::string>(pJson["duration"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson["status"].asInt64());
        }
    }
}

void Train::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trip_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            starttime_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            endtime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            duration_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
}

void Train::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trip"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["trip"].isNull())
        {
            trip_=std::make_shared<std::string>(pJson["trip"].asString());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("carriage"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["carriage"].isNull())
        {
            carriage_=std::make_shared<int8_t>((int8_t)pJson["carriage"].asInt64());
        }
    }
    if(pJson.isMember("startStation"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["startStation"].isNull())
        {
            startstation_=std::make_shared<std::string>(pJson["startStation"].asString());
        }
    }
    if(pJson.isMember("endStation"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["endStation"].isNull())
        {
            endstation_=std::make_shared<std::string>(pJson["endStation"].asString());
        }
    }
    if(pJson.isMember("startTime"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["startTime"].isNull())
        {
            starttime_=std::make_shared<std::string>(pJson["startTime"].asString());
        }
    }
    if(pJson.isMember("endTime"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["endTime"].isNull())
        {
            endtime_=std::make_shared<std::string>(pJson["endTime"].asString());
        }
    }
    if(pJson.isMember("duration"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["duration"].isNull())
        {
            duration_=std::make_shared<std::string>(pJson["duration"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson["status"].asInt64());
        }
    }
}

const int32_t &Train::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Train::getId() const noexcept
{
    return id_;
}
void Train::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Train::PrimaryKeyType & Train::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Train::getValueOfTrip() const noexcept
{
    const static std::string defaultValue = std::string();
    if(trip_)
        return *trip_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getTrip() const noexcept
{
    return trip_;
}
void Train::setTrip(const std::string &pTrip) noexcept
{
    trip_ = std::make_shared<std::string>(pTrip);
    dirtyFlag_[1] = true;
}
void Train::setTrip(std::string &&pTrip) noexcept
{
    trip_ = std::make_shared<std::string>(std::move(pTrip));
    dirtyFlag_[1] = true;
}

const std::string &Train::getValueOfType() const noexcept
{
    const static std::string defaultValue = std::string();
    if(type_)
        return *type_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getType() const noexcept
{
    return type_;
}
void Train::setType(const std::string &pType) noexcept
{
    type_ = std::make_shared<std::string>(pType);
    dirtyFlag_[2] = true;
}
void Train::setType(std::string &&pType) noexcept
{
    type_ = std::make_shared<std::string>(std::move(pType));
    dirtyFlag_[2] = true;
}

const int8_t &Train::getValueOfCarriage() const noexcept
{
    const static int8_t defaultValue = int8_t();
    if(carriage_)
        return *carriage_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Train::getCarriage() const noexcept
{
    return carriage_;
}
void Train::setCarriage(const int8_t &pCarriage) noexcept
{
    carriage_ = std::make_shared<int8_t>(pCarriage);
    dirtyFlag_[3] = true;
}

const std::string &Train::getValueOfStartstation() const noexcept
{
    const static std::string defaultValue = std::string();
    if(startstation_)
        return *startstation_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getStartstation() const noexcept
{
    return startstation_;
}
void Train::setStartstation(const std::string &pStartstation) noexcept
{
    startstation_ = std::make_shared<std::string>(pStartstation);
    dirtyFlag_[4] = true;
}
void Train::setStartstation(std::string &&pStartstation) noexcept
{
    startstation_ = std::make_shared<std::string>(std::move(pStartstation));
    dirtyFlag_[4] = true;
}

const std::string &Train::getValueOfEndstation() const noexcept
{
    const static std::string defaultValue = std::string();
    if(endstation_)
        return *endstation_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getEndstation() const noexcept
{
    return endstation_;
}
void Train::setEndstation(const std::string &pEndstation) noexcept
{
    endstation_ = std::make_shared<std::string>(pEndstation);
    dirtyFlag_[5] = true;
}
void Train::setEndstation(std::string &&pEndstation) noexcept
{
    endstation_ = std::make_shared<std::string>(std::move(pEndstation));
    dirtyFlag_[5] = true;
}

const std::string &Train::getValueOfStarttime() const noexcept
{
    const static std::string defaultValue = std::string();
    if(starttime_)
        return *starttime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getStarttime() const noexcept
{
    return starttime_;
}
void Train::setStarttime(const std::string &pStarttime) noexcept
{
    starttime_ = std::make_shared<std::string>(pStarttime);
    dirtyFlag_[6] = true;
}
void Train::setStarttime(std::string &&pStarttime) noexcept
{
    starttime_ = std::make_shared<std::string>(std::move(pStarttime));
    dirtyFlag_[6] = true;
}

const std::string &Train::getValueOfEndtime() const noexcept
{
    const static std::string defaultValue = std::string();
    if(endtime_)
        return *endtime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getEndtime() const noexcept
{
    return endtime_;
}
void Train::setEndtime(const std::string &pEndtime) noexcept
{
    endtime_ = std::make_shared<std::string>(pEndtime);
    dirtyFlag_[7] = true;
}
void Train::setEndtime(std::string &&pEndtime) noexcept
{
    endtime_ = std::make_shared<std::string>(std::move(pEndtime));
    dirtyFlag_[7] = true;
}

const std::string &Train::getValueOfDuration() const noexcept
{
    const static std::string defaultValue = std::string();
    if(duration_)
        return *duration_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Train::getDuration() const noexcept
{
    return duration_;
}
void Train::setDuration(const std::string &pDuration) noexcept
{
    duration_ = std::make_shared<std::string>(pDuration);
    dirtyFlag_[8] = true;
}
void Train::setDuration(std::string &&pDuration) noexcept
{
    duration_ = std::make_shared<std::string>(std::move(pDuration));
    dirtyFlag_[8] = true;
}

const int8_t &Train::getValueOfStatus() const noexcept
{
    const static int8_t defaultValue = int8_t();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Train::getStatus() const noexcept
{
    return status_;
}
void Train::setStatus(const int8_t &pStatus) noexcept
{
    status_ = std::make_shared<int8_t>(pStatus);
    dirtyFlag_[9] = true;
}

void Train::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Train::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "trip",
        "type",
        "carriage",
        "startStation",
        "endStation",
        "startTime",
        "endTime",
        "duration",
        "status"
    };
    return inCols;
}

void Train::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrip())
        {
            binder << getValueOfTrip();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCarriage())
        {
            binder << getValueOfCarriage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStartstation())
        {
            binder << getValueOfStartstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndstation())
        {
            binder << getValueOfEndstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStarttime())
        {
            binder << getValueOfStarttime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEndtime())
        {
            binder << getValueOfEndtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDuration())
        {
            binder << getValueOfDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Train::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void Train::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrip())
        {
            binder << getValueOfTrip();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCarriage())
        {
            binder << getValueOfCarriage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStartstation())
        {
            binder << getValueOfStartstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndstation())
        {
            binder << getValueOfEndstation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStarttime())
        {
            binder << getValueOfStarttime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEndtime())
        {
            binder << getValueOfEndtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDuration())
        {
            binder << getValueOfDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Train::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrip())
    {
        ret["trip"]=getValueOfTrip();
    }
    else
    {
        ret["trip"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getCarriage())
    {
        ret["carriage"]=getValueOfCarriage();
    }
    else
    {
        ret["carriage"]=Json::Value();
    }
    if(getStartstation())
    {
        ret["startStation"]=getValueOfStartstation();
    }
    else
    {
        ret["startStation"]=Json::Value();
    }
    if(getEndstation())
    {
        ret["endStation"]=getValueOfEndstation();
    }
    else
    {
        ret["endStation"]=Json::Value();
    }
    if(getStarttime())
    {
        ret["startTime"]=getValueOfStarttime();
    }
    else
    {
        ret["startTime"]=Json::Value();
    }
    if(getEndtime())
    {
        ret["endTime"]=getValueOfEndtime();
    }
    else
    {
        ret["endTime"]=Json::Value();
    }
    if(getDuration())
    {
        ret["duration"]=getValueOfDuration();
    }
    else
    {
        ret["duration"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

Json::Value Train::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTrip())
            {
                ret[pMasqueradingVector[1]]=getValueOfTrip();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getType())
            {
                ret[pMasqueradingVector[2]]=getValueOfType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCarriage())
            {
                ret[pMasqueradingVector[3]]=getValueOfCarriage();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStartstation())
            {
                ret[pMasqueradingVector[4]]=getValueOfStartstation();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEndstation())
            {
                ret[pMasqueradingVector[5]]=getValueOfEndstation();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStarttime())
            {
                ret[pMasqueradingVector[6]]=getValueOfStarttime();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEndtime())
            {
                ret[pMasqueradingVector[7]]=getValueOfEndtime();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getDuration())
            {
                ret[pMasqueradingVector[8]]=getValueOfDuration();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[9]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrip())
    {
        ret["trip"]=getValueOfTrip();
    }
    else
    {
        ret["trip"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getCarriage())
    {
        ret["carriage"]=getValueOfCarriage();
    }
    else
    {
        ret["carriage"]=Json::Value();
    }
    if(getStartstation())
    {
        ret["startStation"]=getValueOfStartstation();
    }
    else
    {
        ret["startStation"]=Json::Value();
    }
    if(getEndstation())
    {
        ret["endStation"]=getValueOfEndstation();
    }
    else
    {
        ret["endStation"]=Json::Value();
    }
    if(getStarttime())
    {
        ret["startTime"]=getValueOfStarttime();
    }
    else
    {
        ret["startTime"]=Json::Value();
    }
    if(getEndtime())
    {
        ret["endTime"]=getValueOfEndtime();
    }
    else
    {
        ret["endTime"]=Json::Value();
    }
    if(getDuration())
    {
        ret["duration"]=getValueOfDuration();
    }
    else
    {
        ret["duration"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

bool Train::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("trip"))
    {
        if(!validJsonOfField(1, "trip", pJson["trip"], err, true))
            return false;
    }
    else
    {
        err="The trip column cannot be null";
        return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(2, "type", pJson["type"], err, true))
            return false;
    }
    else
    {
        err="The type column cannot be null";
        return false;
    }
    if(pJson.isMember("carriage"))
    {
        if(!validJsonOfField(3, "carriage", pJson["carriage"], err, true))
            return false;
    }
    if(pJson.isMember("startStation"))
    {
        if(!validJsonOfField(4, "startStation", pJson["startStation"], err, true))
            return false;
    }
    else
    {
        err="The startStation column cannot be null";
        return false;
    }
    if(pJson.isMember("endStation"))
    {
        if(!validJsonOfField(5, "endStation", pJson["endStation"], err, true))
            return false;
    }
    else
    {
        err="The endStation column cannot be null";
        return false;
    }
    if(pJson.isMember("startTime"))
    {
        if(!validJsonOfField(6, "startTime", pJson["startTime"], err, true))
            return false;
    }
    else
    {
        err="The startTime column cannot be null";
        return false;
    }
    if(pJson.isMember("endTime"))
    {
        if(!validJsonOfField(7, "endTime", pJson["endTime"], err, true))
            return false;
    }
    else
    {
        err="The endTime column cannot be null";
        return false;
    }
    if(pJson.isMember("duration"))
    {
        if(!validJsonOfField(8, "duration", pJson["duration"], err, true))
            return false;
    }
    else
    {
        err="The duration column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(9, "status", pJson["status"], err, true))
            return false;
    }
    return true;
}
bool Train::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Train::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("trip"))
    {
        if(!validJsonOfField(1, "trip", pJson["trip"], err, false))
            return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(2, "type", pJson["type"], err, false))
            return false;
    }
    if(pJson.isMember("carriage"))
    {
        if(!validJsonOfField(3, "carriage", pJson["carriage"], err, false))
            return false;
    }
    if(pJson.isMember("startStation"))
    {
        if(!validJsonOfField(4, "startStation", pJson["startStation"], err, false))
            return false;
    }
    if(pJson.isMember("endStation"))
    {
        if(!validJsonOfField(5, "endStation", pJson["endStation"], err, false))
            return false;
    }
    if(pJson.isMember("startTime"))
    {
        if(!validJsonOfField(6, "startTime", pJson["startTime"], err, false))
            return false;
    }
    if(pJson.isMember("endTime"))
    {
        if(!validJsonOfField(7, "endTime", pJson["endTime"], err, false))
            return false;
    }
    if(pJson.isMember("duration"))
    {
        if(!validJsonOfField(8, "duration", pJson["duration"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(9, "status", pJson["status"], err, false))
            return false;
    }
    return true;
}
bool Train::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Train::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
